apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-server
  namespace: apache-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-server
  template:
    metadata:
      labels:
        app: apache-server
    spec:
      containers:
      - name: apache
        image: satishthapak/argocd:b6c7eb56e79e5db0fbb987ad8f1a3aa3622dc88a 
        ports:
        - containerPort: 80
