apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-server
  namespace: apache-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-server
  template:
    metadata:
      labels:
        app: apache-server
    spec:
      containers:
      - name: apache
        image: satishthapak/apache-demo:latest
        ports:
        - containerPort: 80
