apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  labels:
    app: node-app
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - port: 80            # External port exposed by the service
      targetPort: 3000    # Internal port your app listens on
      nodePort: 30080     # Optional: fixed NodePort (range: 30000–32767)
