name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image with tags
      run: |
        docker build -t satishthapak/argocd:${{ github.sha }} -t satishthapak/argocd:latest .
        docker images

    - name: Push Docker image with commit SHA tag
      run: docker push satishthapak/argocd:${{ github.sha }}

    - name: Push Docker image with latest tag
      run: docker push satishthapak/argocd:latest
